### ISSUE TITLE
src/blas.c:317:6: error: redefinition of ‘variance_cpu’

### ISSUE THREAD

**Issue by dfy888** [BBuf/Darknet#4]
Darknet-BBuf/src/blas.c:317:6: error: redefinition of ‘variance_cpu’
 void variance_cpu(float *x, float *mean, int batch, int filters, int spatial, float *variance)
      ^~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.

**Comment by dfy888** [comment]
搞定了

**Comment by douyueyang** [comment]
怎么搞定的
